#!/usr/bin/env bash
# Deploy the Prometheus + Grafana monitoring stack and wire it to the dashboard.
#
# What it does, in order:
#   1. Checks Docker and the compose plugin are usable.
#   2. Creates deploy/monitoring-stack/.env if missing, generating a strong
#      Grafana admin password (printed once).
#   3. Validates and brings the stack up.
#   4. Waits for Prometheus and Grafana to report healthy.
#   5. Points the dashboard at Prometheus by setting PROMETHEUS_URL and
#      GRAFANA_URL in the dashboard's own .env — so the dashboard switches
#      from its local SQLite history to Prometheus on the next restart.
#
# It is idempotent: re-running reuses the existing password and .env, and
# `docker compose up -d` only recreates what changed.
#
# Read-only toward the host: it reads /proc and /sys through the exporters and
# never writes to the array or existing services. Everything binds to
# 127.0.0.1 — nothing here is reachable from another VLAN.
set -euo pipefail

STACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# deploy/monitoring-stack -> deploy -> <dashboard root>
DASHBOARD_ROOT="$(cd "$STACK_DIR/../.." && pwd)"
DASHBOARD_ENV="${DASHBOARD_ROOT}/.env"

PROM_URL_INTERNAL="http://127.0.0.1:9090"
GRAFANA_URL_INTERNAL="http://127.0.0.1:3000"

say()  { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
ok()   { printf '   \033[1;32m✓\033[0m %s\n' "$*"; }
warn() { printf '   \033[1;33m!\033[0m %s\n' "$*"; }
die()  { printf '\n\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# --------------------------------------------------------------------------
# 1. Prerequisites
# --------------------------------------------------------------------------
say "Checking prerequisites"
command -v docker >/dev/null 2>&1 || die "docker is not installed."
docker compose version >/dev/null 2>&1 \
  || die "the docker compose plugin is not available (need Compose v2)."
docker info >/dev/null 2>&1 \
  || die "cannot talk to the Docker daemon — is it running, and are you in the docker group?"
ok "Docker and Compose are usable."

cd "$STACK_DIR"

# --------------------------------------------------------------------------
# 2. Secrets
# --------------------------------------------------------------------------
say "Preparing secrets"
if [ ! -f .env ]; then
    password="$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 24)"
    umask 077
    cat > .env <<EOF
# Generated by deploy.sh on $(date -Iseconds). Do not commit.
GRAFANA_ADMIN_PASSWORD=${password}
EOF
    chmod 600 .env
    ok "Created .env with a generated Grafana admin password."
    GENERATED_PASSWORD="$password"
else
    ok ".env already exists — reusing it."
    if ! grep -q '^GRAFANA_ADMIN_PASSWORD=..' .env; then
        die "GRAFANA_ADMIN_PASSWORD is empty in .env. Set it, then re-run."
    fi
    GENERATED_PASSWORD=""
fi

# --------------------------------------------------------------------------
# 3. Validate and start
# --------------------------------------------------------------------------
say "Validating the compose file"
docker compose config >/dev/null || die "docker compose config failed — see the error above."
ok "Compose file is valid."

say "Starting the stack (this pulls images on first run)"
docker compose up -d
ok "Containers started."

# --------------------------------------------------------------------------
# 4. Wait for health
# --------------------------------------------------------------------------
wait_for() {
    local name="$1" url="$2" tries=60
    printf '   waiting for %s ' "$name"
    while [ "$tries" -gt 0 ]; do
        if curl -fsS -o /dev/null --max-time 3 "$url" 2>/dev/null; then
            printf ' ready\n'; return 0
        fi
        printf '.'; sleep 2; tries=$((tries - 1))
    done
    printf ' timed out\n'
    return 1
}

say "Waiting for services to come up"
wait_for "Prometheus" "${PROM_URL_INTERNAL}/-/healthy" \
    && ok "Prometheus healthy at ${PROM_URL_INTERNAL}" \
    || warn "Prometheus did not report healthy yet — check: docker compose logs prometheus"
wait_for "Grafana" "${GRAFANA_URL_INTERNAL}/api/health" \
    && ok "Grafana healthy at ${GRAFANA_URL_INTERNAL}" \
    || warn "Grafana did not report healthy yet — check: docker compose logs grafana"

# Surface how many targets Prometheus is actually scraping, so a stack that
# is "up" but scraping nothing is visible immediately rather than at first
# empty graph.
if command -v curl >/dev/null 2>&1; then
    up_count="$(curl -fsS --max-time 5 "${PROM_URL_INTERNAL}/api/v1/query?query=up" 2>/dev/null \
        | grep -o '"value"' | wc -l || echo 0)"
    ok "Prometheus reports ${up_count} scrape target series (expect a handful once warmed up)."
fi

# --------------------------------------------------------------------------
# 5. Wire the dashboard to Prometheus
# --------------------------------------------------------------------------
say "Pointing the dashboard at Prometheus"
upsert_env() {
    local key="$1" value="$2" file="$3"
    touch "$file"; chmod 600 "$file"
    if grep -q "^${key}=" "$file"; then
        # Portable in-place edit (BSD/GNU sed differ on -i).
        local tmp; tmp="$(mktemp)"
        sed "s|^${key}=.*|${key}=${value}|" "$file" > "$tmp" && mv "$tmp" "$file"
        chmod 600 "$file"
    else
        printf '%s=%s\n' "$key" "$value" >> "$file"
    fi
}

if [ -w "$DASHBOARD_ROOT" ] || [ -f "$DASHBOARD_ENV" ]; then
    upsert_env "PROMETHEUS_URL" "$PROM_URL_INTERNAL" "$DASHBOARD_ENV"
    upsert_env "GRAFANA_URL" "$GRAFANA_URL_INTERNAL" "$DASHBOARD_ENV"
    ok "Set PROMETHEUS_URL and GRAFANA_URL in ${DASHBOARD_ENV}"
else
    warn "Could not write ${DASHBOARD_ENV}. Add these two lines yourself:"
    printf '       PROMETHEUS_URL=%s\n       GRAFANA_URL=%s\n' \
        "$PROM_URL_INTERNAL" "$GRAFANA_URL_INTERNAL"
fi

# --------------------------------------------------------------------------
# Done
# --------------------------------------------------------------------------
say "Done"
cat <<EOF
   The monitoring stack is running, all bound to 127.0.0.1:

     Prometheus   ${PROM_URL_INTERNAL}
     Grafana      ${GRAFANA_URL_INTERNAL}   (admin / see below)
     node         127.0.0.1:9100
     cAdvisor     127.0.0.1:9101
     blackbox     127.0.0.1:9115
     smartctl     127.0.0.1:9633

EOF
if [ -n "$GENERATED_PASSWORD" ]; then
    printf '   \033[1;33mGrafana admin password (shown once):\033[0m %s\n\n' "$GENERATED_PASSWORD"
    printf '   It is stored in %s/.env (mode 600). Change it at first login.\n\n' "$STACK_DIR"
fi
cat <<EOF
   Next:
     * Restart the dashboard so it picks up PROMETHEUS_URL:
         sudo systemctl restart streamanator-dashboard
       (or ./scripts/restart-dev.sh if it is running detached)
     * The dashboard's Diagnostics page will now show Prometheus as the
       telemetry source, and SMART/CRC history begins accruing immediately.

   Grafana is reachable only from this host. To view it from your desktop,
   tunnel it — do NOT open port 3000 on any VLAN:
     ssh -L 3000:127.0.0.1:3000 arm@10.0.40.100
   then browse http://localhost:3000
EOF
